### ISSUE TITLE
How do I remove email quotas?

### ISSUE THREAD

**Issue by JemiloII** [louis-lau/DuckyAPI#16]
Ducky is setting default quotas, I don't want any of these. Just want them to be unlimited.

**Comment by louis-lau** [comment]
Duckyapi currently sets the default quota of a new email account to the quota of the package of the duckyapi user. If the duckyapi user has no quota/package assigned, duckyapi does not set it at all. I believe wildduck does this, you can test this by using the wildduck api directly.

I don't believe wildduck currently supports unlimited storage quota. You may reopen this issue there :). In the meantime you can just set a really high quota.

**Comment by JemiloII** [comment]
ahh, thanks!
