### ISSUE TITLE
Disable redis from DuckyApi

### ISSUE THREAD

**Issue by R4Ajeti** [louis-lau/DuckyAPI#18]
Hi,
I followed steps here to install DuckyApi:
https://github.com/louis-lau/DuckyAPI/blob/master/README.md#integrated-duckypanel

This is my error output:
"
[
  {
    "property": "TOKEN_SECRET",
    "children": [],
    "constraints": {
      "notContains": "Set TOKEN_SECRET to something safe and random!"
    }
  },
  {
    "property": "REDIS_URL",
    "children": [],
    "constraints": {
      "isString": "REDIS_URL must be a string",
      "isNotEmpty": "REDIS_URL should not be empty"
    }
  }
]
"

Is there anyway i can disable redis completely

Happy coding :)

**Comment by louis-lau** [comment]
> Set TOKEN_SECRET to something safe and random!

Did you set token_secret to something safe and random?

> Is there anyway i can disable redis completely

I wouldn't make it required config if it didn't need it ;)

WildDuck also need redis, so you can just use the same server. Just make sure you choose a different database number.
