### ISSUE TITLE
Unable to get result, forbidden

### ISSUE THREAD

**Issue by blackyzero** [louis-lau/DuckyAPI#5]
Hello,

I setup DuckyAPI on different server, and try to query to wildduck server, but i got forbidden server respond when trying to get domain list, here is detail:

{
  "statusCode": 403,
  "error": "PermissionForbiddenError",
  "message": "You do not have the permission to access this resource."
}

How could i solve it?
Thanks a lot.

**Comment by louis-lau** [comment]
Tha admin user is only meant for administering the duckyapi users, not for adding domains etc. You need to create a package and a user first like in the readme, then you use that user with the rest of the api.

Any methods meant for the admin user are marked with [Admin only] in the documentation.

**Comment by blackyzero** [comment]
Thanks @louis-lau for reply.
I followed instruction, already create normal user, but i don't know if it's good.
Do i need to authorize first on "swagger" page, if yes then which value should i input ?

In addition, i would need to use DuckyPanel to manage Wildduck mail server, but it seems unable to connect to Wildduck mail server at moment. There is no info or record showing on DuckyPanel.

Please help.
Thank you.

**Comment by louis-lau** [comment]
You need to post to /authentication to create an access token, which can then be used to authorize. DuckyPanel doesn't connect to WildDuck, it connects to DuckyApi.

To manage existing wildduck accounts with DuckyApi you will need to add a special tag to them with this format: `domain:example.com`. That will make the account available to be managed by the user with the example.com. The same goes for forwarders. May need to add this to the readme at some point 😁

**Comment by blackyzero** [comment]
Thanks @louis-lau for quick respond.
> You need to post to /authentication to create an access token
i use the regular account which was created in instruction steps, then i can get access token. Then i use it for "authorize"

If i understand correctly, i need to add special tag for my domain on Wildduck server, then how could i add tag for my existing domain, ex: domain1.com

In addition, on Wildduck server, do i need to add token in following files:
/etc/wildduck/wildduck-webmail.toml
/etc/wildduck/api.toml

If yes, please show me which one should i add?

Thanks a lot.

**Comment by louis-lau** [comment]
You can add the tags using the WildDuck api: https://docs.wildduck.email/api/#api-Users-PutUser

The token you set in api.toml is what secures the WildDuck api. Both WildDuck webmail and DuckyApi need this access token in their config to have access to the WildDuck api. You can set it to whatever you want. This has nothing to do with the access token created when you authenticate in DuckyApi.

**Comment by blackyzero** [comment]
thanks @louis-lau 
I added tag for my test account, it shows success

Then i come back to DuckyAPI, and try to list account, but the responds show me empty []
Is it normal?

For API, i commented in them in wildduck-webmail.toml, and leave the default in api.toml file
(secret="a secret cat")

I also tried to refresh DuckyPanel, but still same result, not show any info.

Please advice how could i make it works.
Thank you.

**Comment by louis-lau** [comment]
Did you set WILDDUCK_API_TOKEN to "a secret cat" as well in the config? If yes, that should be good.

Did you add the domain to the user? This can be done in DuckyPanel or DuckyApi.

**Comment by louis-lau** [comment]
And yes, [] is normal for 0 email account. So this means you either haven't added the domain or you haven't added the right tag to the accounts.

**Comment by blackyzero** [comment]
i haven't add any new domain, only the default domain when i installed Wildduck.
Do i need to add one more domain?

I set WILDDUCK_API_TOKEN to "a secret cat" in DuckyAPI config, but responds still []

How could i add domain to the user by DuckyPanel or DuckyAPI?

Thank you.

**Comment by louis-lau** [comment]
By going to domains and clicking the +

**Comment by blackyzero** [comment]
i got stuck with that, please take a look test url
Here is my DuckyPanel: http://8.9.30.226:4201
DuckyAPI: http://8.9.30.226:3000/
Access token is: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZWJlOWM0NGQzY2RhNzgzMzQxYTAwZmEiLCJ0eXBlIjoiYWNjZXNzX3Rva2VuIiwiaWF0IjoxNTg5NTUxNzkyLCJleHAiOjE1ODk1ODA1OTIsImp0aSI6IkdkeTk1TktuNlRfM1NUc3Y3UWJndiJ9.sL0JgloNwyaJQ3N_wLW29pZdc5L2y1uJfPzDvBN7j2o

**Comment by blackyzero** [comment]
i use reverse proxy for DuckyPanel, cause it's always listening on localhost:4200, i don't know how to bind it using public ip.

**Comment by louis-lau** [comment]
Duckypanel is trying to connect to http://localhost:3000/ from your browser, which it obviously can't. As per the readme of DuckyPanel: "Don't forget to change the url to DuckyAPI in src/app/app.module.ts". You need to change it to http://8.9.30.226:3000/.

**Comment by louis-lau** [comment]
> i use reverse proxy for DuckyPanel, cause it's always listening on localhost:4200, i don't know how to bind it using public ip.

Please read the readme again. The development server is for development and testing. You can server duckypanel with any webserver by serving the files that get built to the `dist` directory. You will need to rewrite requests to index.html.

Though the dev server is fine for testing.

**Comment by louis-lau** [comment]
Here is an example for nginx:
https://www.devdungeon.com/content/deploy-angular-apps-nginx

**Comment by blackyzero** [comment]
it's listening on all ip for DuckyAPI:

node      34410            root   24u  IPv6 605002      0t0  TCP *:3000 (LISTEN)

For nginx, i follow your given instruction. Thanks for this pointing, but i still get issue ...

**Comment by louis-lau** [comment]
Duckypanel is still trying http://localhost:3000. You didn't do it correctly. You can see this by opening the dev console in your browser.

**Comment by louis-lau** [comment]
You can reverse proxy duckyapi like any other application. Is it a problem that it's listening on all interfaces?

**Comment by blackyzero** [comment]
You're right. i see it. I need to build DuckyPanel again to change to public ip.
But i still face another issue "500 (Internal Server Error)"

From console of DuckyAPI, i get some logs:

[Nest] 34410   - 05/15/2020, 4:16:28 PM   [ForwardersService] Request failed with status code 403 +52241ms
[Nest] 34410   - 05/15/2020, 4:16:28 PM   [AccountsService] Request failed with status code 403 +4ms
[Nest] 34410   - 05/15/2020, 4:16:28 PM   [DkimService] Request failed with status code 403 +4ms

**Comment by louis-lau** [comment]
That means it's getting a 403 from whatever url you set in WILDDUCK_API_URL. Are you sure the url is right?

**Comment by blackyzero** [comment]
yes, it's right Wildduck api url.
I also post the config here, maybe i still did wrong at some points, please take a look. Thanks a lot

`# Custom Base URL; Optional; Default "/"
# BASE_URL=/

# JWT secret value. Set this to something safe and random. Should be the same accross all instances; Required
TOKEN_SECRET=CHANGE0ME0PLEASE!

# MongoDB connection string. This can include authentication, ports, database name, multiple hosts for replica sets etc
# https://docs.mongodb.com/manual/reference/connection-string/
# https://www.iana.org/assignments/uri-schemes/prov/mongodb
# MongoDB is used to store API users and their domains; Required
MONGODB_URL=mongodb://localhost:27017/ducky-api

# Redis connection string. Only supports a single redis instance, sentinel support will be added in the future.
# https://www.iana.org/assignments/uri-schemes/prov/redis
# Redis is used for task queue management; Required
#REDIS_URL=redis://localhost/10
REDIS_URL=redis://localhost/10

# URL for the WildDuck API; Required
#WILDDUCK_API_URL=http://localhost:5438
WILDDUCK_API_URL=http://air.oios.net:8080

# Token for authenticating against the WildDuck API; Required
#WILDDUCK_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZWJjYWE2NzMzYjkzYjQ0ODlmOGY1ZjMiLCJ0eXBlIjoiYXBpX2tleSIsImlhdCI6MTU4OTQyMjc1NCwiZXhwIjo0NzQzMDIyNzU0LCJqdGkiOiJyOHNKZXNwNEVhSlE0U1VHT3NYdE8ifQ.Ma6OFKxol56kX1mHpWJIa2dgDF30cUOgGum5OGENAus
WILDDUCK_API_TOKEN="a secret cat"

# If set to false WildDuck will check all new passwords against https://haveibeenpwned.com/Passwords; Optional; Default true
# ALLOW_UNSAFE_ACCOUNT_PASSWORDS=true

# Allow values such as *@example.com. user@* is never allowed; Optional; Default true
# ALLOW_FORWARDER_WILDCARD=true

# Array of MX record objects. These are suggested and checked in dnscheck; Required
#MX_RECORDS=[{"exchange": "mx1.example.com", "priority": 10}, {"exchange": "mx2.example.com", "priority": 20}]
MX_RECORDS=[{"exchange": "air.oios.net", "priority": 5}, {"exchange": "mx2.example.com", "priority": 20}]

# SPF value to suggest in dnscheck; Required
SPF_CORRECT_VALUE=v=spf1 include:air.oios.net -all

# Regex to test spf against in dnscheck; Optional
SPF_REGEX=^v=spf.* include:oios.net.*(-|~|\\?)all$`

**Comment by louis-lau** [comment]
http://air.oios.net:8080/ is not reachable for me, is it reachable for the server?

**Comment by blackyzero** [comment]
yes, cause of firewall rule. i can reach from server with DuckAPI/Panel server.
You can try again, i just whiltelist access from you.

Thank you.

**Comment by louis-lau** [comment]
![image](https://user-images.githubusercontent.com/1346804/82074723-7a2d1300-96db-11ea-8940-9ac634067a2f.png)

Did you restart WildDuck after setting the access token?

**Comment by blackyzero** [comment]
i just restart both wildduck and wildduck-webmail service.

**Comment by louis-lau** [comment]
You may need to enable access control in the wildduck config, as it's still not accepting the token

**Comment by blackyzero** [comment]
please show me how to enable it.

**Comment by louis-lau** [comment]
You should really be able to find this yourself. in api.toml:
```
[accessControl]
# If true then require a valid access token to perform API calls
# If a client provides a token then it is validated even if using a token is not required
enabled=false
```
Set it to true

**Comment by blackyzero** [comment]
yup, i set it to true, and restart both wildduck and wildduck-webmail service.
But it seems the error still happening.

**Comment by louis-lau** [comment]
secret is different from accessToken. Did you set the accessToken?

**Comment by blackyzero** [comment]
seems like it's been set same, and this is error.

Which access token should i use to set to match them all?

in api.toml
-------------------
[accessControl]
# If true then require a valid access token to perform API calls
# If a client provides a token then it is validated even if using a token is not required
enabled=true

# Secret for HMAC
# Changing this value invalidates all tokens
secret="a secret cat"
----------------------

wildduck-webmail.toml
----------------------
[api]
    url="http://8.9.30.37:8080"
#        accessToken=


and DuckyAPI config,
----------------------
# JWT secret value. Set this to something safe and random. Should be the same accross all instances; Required
TOKEN_SECRET=CHANGE0ME0PLEASE!

WILDDUCK_API_TOKEN="a secret cat"
------------------------

**Comment by louis-lau** [comment]
The  access token should be the same everywhere. The only thing I see here is the secret, and the access token being empty in the webmail config.

Tha cess token is _not_ the secret

**Comment by louis-lau** [comment]
Also, try using code blocks:
https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by blackyzero** [comment]
i set same API token in wildduck-webmail.toml and DuckyAPI to this one, but still get same error.

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZWJjYWE2NzMzYjkzYjQ0ODlmOGY1ZjMiLCJ0eXBlIjoiYXBpX2tleSIsImlhdCI6MTU4OTQyMjc1NCwiZXhwIjo0NzQzMDIyNzU0LCJqdGkiOiJyOHNKZXNwNEVhSlE0U1VHT3NYdE8ifQ.Ma6OFKxol56kX1mHpWJIa2dgDF30cUOgGum5OGENAus
```

**Comment by louis-lau** [comment]
You NEED to set it in api.toml. This secures the WILDDUCK api, it doesn not secure webmail or duckyapi. BUT, webmail and duckyapi need it to ACCESS wildduck.

Please set it in api.toml.

**Comment by blackyzero** [comment]
perfect. it works now. Thanks so much. There is no Internal Error issue any more.
Still having another error, but i guess it's related.

```
Error: <circle> attribute r: A negative value is not valid. ("-5")
setAttribute @ platform-browser.js:2879
setAttribute @ animations.js:539
setAttribute @ core.js:45865
setElementAttribute @ core.js:43042
checkAndUpdateElementValue @ core.js:43005
checkAndUpdateElementInline @ core.js:42947
checkAndUpdateNodeInline @ core.js:44363
checkAndUpdateNode @ core.js:44306
debugCheckAndUpdateNode @ core.js:45328
debugCheckRenderNodeFn @ core.js:45306
eval @ MatSpinner.html:1
debugUpdateRenderer @ core.js:45294
checkAndUpdateView @ core.js:44277
callViewAction @ core.js:44637
execEmbeddedViewsAction @ core.js:44594
checkAndUpdateView @ core.js:44272
callViewAction @ core.js:44637
execComponentViewsAction @ core.js:44565
checkAndUpdateView @ core.js:44278
callViewAction @ core.js:44637
execComponentViewsAction @ core.js:44565
checkAndUpdateView @ core.js:44278
callViewAction @ core.js:44637
execComponentViewsAction @ core.js:44565
checkAndUpdateView @ core.js:44278
callViewAction @ core.js:44637
execEmbeddedViewsAction @ core.js:44594
checkAndUpdateView @ core.js:44272
callViewAction @ core.js:44637
execComponentViewsAction @ core.js:44565
checkAndUpdateView @ core.js:44278
callWithDebugContext @ core.js:45632
debugCheckAndUpdateView @ core.js:45194
detectChanges @ core.js:31126
tick @ core.js:41045
(anonymous) @ core.js:40893
invoke @ zone-evergreen.js:365
onInvoke @ core.js:39699
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:124
run @ core.js:39511
next @ core.js:40890
schedulerFn @ core.js:35336
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:35298
checkStable @ core.js:39642
onHasTask @ core.js:39719
hasTask @ zone-evergreen.js:420
_updateTaskCount @ zone-evergreen.js:441
_updateTaskCount @ zone-evergreen.js:264
runTask @ zone-evergreen.js:185
drainMicroTaskQueue @ zone-evergreen.js:570
invokeTask @ zone-evergreen.js:485
invokeTask @ zone-evergreen.js:1596
globalZoneAwareCallback @ zone-evergreen.js:1622
Show 29 more frames
```

**Comment by louis-lau** [comment]
Yeah, that's related to the library I use for loading animations on the buttons. You can ignore it 😁

**Comment by louis-lau** [comment]
Once you get all of this working you will need to change your TOKEN_SECRET and the wildduck secret as well. If I know the TOKEN_SECRET I can gain access to any account in duckyapi (there's a reason it's called a secret 😉). Note that changing the TOKEN_SECRET will invalidate all duckyapi access tokens and api keys.

If I were you I would change the WildDuck accessToken as well, though that isn't as much of a problem seeing as you've firewalled that off.

**Comment by blackyzero** [comment]
I see. Thanks a lot for your advice @louis-lau 
This is very great and useful tool to manage Wildduck mail.

**Comment by louis-lau** [comment]
Good to hear! 😁
