### ISSUE TITLE
Unable to create admin user

### ISSUE THREAD

**Issue by skerit** [louis-lau/DuckyAPI#6]
I'm trying to create a new admin user just the way the example states in the README, but I get this error:

```
node dist/cli create-admin skerit
✖ Failed creating admin user with username: "skerit" and password: "[object Object]":
InternalServerErrorException: Unknown error
    at UsersService.<anonymous> (/opt/duckyapi/dist/cli.js:604:35)
    at Generator.throw (<anonymous>)
    at rejected (/opt/duckyapi/dist/cli.js:395:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  response: {
    statusCode: 500,
    message: 'Unknown error',
    error: 'Internal Server Error'
  },
  status: 500
}
```

**Comment by louis-lau** [comment]
Well shite, seems my dependency update borked that yesterday and I didn't catch it. I swear I _will_ add tests one day 😂. Let me see if I can fix it.

**Comment by louis-lau** [comment]
There's bug in the library which isn't fixed yet, so I reverted to the previous working version. Make sure to run npm install after you pull the changes. Sorry about that!
