### ISSUE TITLE
Adding users

### ISSUE THREAD

**Issue by Weldeasy** [louis-lau/DuckyAPI#8]
Hello! 

In the request response for creating a new normal user says:

`{
  "statusCode": 400,
  "message": [
    {
      "property": "packageId",
      "children": [],
      "constraints": {
        "isMongoId": "packageId must be a mongodb id"
      }
    }
  ],
  "error": "ValidationError"
}`

I have to specify the new ID?

**Comment by louis-lau** [comment]
Have you pulled the latest changes? I've already made packageId optional: https://github.com/louis-lau/DuckyAPI/blob/b5bca68c73115bf72364466de18d771fccb2cc2e/src/users/dto/create-user.dto.ts#L28

The packageId would be the id of a package you created with certain limits, that will then be applied to the user. But like I said I've made packages optional and a normal user will have no limits by default.

**Comment by Weldeasy** [comment]
I just cloned the repo, a few minuts ago :S

**Comment by louis-lau** [comment]
What data are you sending in the request? Of course you can mask the password :grin:

**Comment by Weldeasy** [comment]
curl -X POST "http://localhost:3300/users" 
-H "Authorization: Bearer TOKEN_FROM_PREVIOUS_COMMAND"
 -H "Content-Type: application/json" -d '{"username":"test", "password":"test"}'

**Comment by Weldeasy** [comment]
the response is: 
{"statusCode":400,"message":"No package found with id undefined","error":"Packag                                                       eNotFoundError"}

**Comment by louis-lau** [comment]
Ah, damn. I made it optional but I didn't remove the packageId check. Damnit. Will fix this later today.

**Comment by Weldeasy** [comment]
No problem! Thanks for the reply, I didn't know if I was missing something!

**Comment by louis-lau** [comment]
Should be fixed now! 😁

**Comment by Weldeasy** [comment]
It is! Thank you!
